openapi: 3.0.0
info:
  title: Skeleton basic API
  description: API docs stub
  version: 0.0.0
servers:
  - url: http://localhost:{port}/{service_name}/v1
    description: Dev env
    variables:
      service_name:
        default: rfskeleton
      port:
        default: '5000'
paths:
  /smoke:
    get:
      summary: Endpoint to ensure service is up.
      responses:
        '200':
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                    example: world

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error_message:
          type: string
  responses:
    '422':
      description: Missing data for required field
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'